language: c

dist: trusty

sudo: required

env:
  - PGVERSION=9.2
  - PGVERSION=9.3
  - PGVERSION=9.4
  - PGVERSION=9.5
  - PGVERSION=9.6

before_script:
  - export PATH=/usr/lib/postgresql/$PGVERSION/bin:$PATH
  - sudo /etc/init.d/postgresql stop
  - sudo /etc/init.d/postgresql start $PGVERSION
  - sudo apt-get install postgresql-server-dev-$PGVERSION
#  - sudo apt-get install postgresql-common

addons:
  apt:
    packages:
      - postgresql-common

script:
  - make && sudo make install DESTDIR=/
  - make installcheck
  - cat results/1*
